version: '3.2'

services:
  coordinator:
    image: "lewuathe/trino-coordinator:${TRINO_VERSION}"
    ports:
      - "8080:8080"
    container_name: "coordinator"
    command: http://coordinator:8080 coordinator
    volumes:
      - ./catalogs:/usr/local/trino/etc/catalog
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 750M
        reservations:
          cpus: '0.25'
          memory: 250M
  worker0:
    image: "lewuathe/trino-worker:${TRINO_VERSION}"
    container_name: "worker0"
    ports:
      - "8081:8081"
    command: http://coordinator:8080 worker0
    volumes:
      - ./catalogs:/usr/local/trino/etc/catalog
    depends_on:
      - "coordinator"
      - "pdb"
      - "mdb"
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 750M
        reservations:
          cpus: '0.25'
          memory: 250M
  # worker1:
  #   image: "lewuathe/trino-worker:${TRINO_VERSION}"
  #   container_name: "worker1"
  #   ports:
  #     - "8082:8081"
  #   command: http://coordinator:8080 worker1
  #   volumes:
  #     - ./catalogs:/usr/local/trino/etc/catalog
  #   depends_on:
  #     - "coordinator"
  #     - "pdb"
  #     - "mdb"
  pdb:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 450M
        reservations:
          cpus: '0.25'
          memory: 250M
  mdb:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: dev
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 450M
        reservations:
          cpus: '0.25'
          memory: 250M
  trino-demo:
    build:
      context: .
    environment:
      NUMOFROWS: "350"
      MYSQL_HOST: mdb
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DB: dev
      POSTGRES_HOST: pdb
      POSTGRES_DB: dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      TRINO_HOST: coordinator
      TRINO_PORT: "8080"
      LIMIT: "200"
    volumes:
      - type: bind
        source: ./demo.sh
        target: /demo.sh
    depends_on:
      - "coordinator"
      - "pdb"
      - "mdb"
      - "worker0"
      # - "worker1"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 450M
        reservations:
          cpus: '0.25'
          memory: 250M
